resources:
  containers:
  - container: ubuntu-build-container
    image: swift:4.2.1

pool:
  vmImage: 'ubuntu-16.04'

container: ubuntu-build-container

steps:
- script: swift build --configuration release --product ExampleResponseApp
  displayName: building application
- task: CopyFiles@2
  inputs:
    targetFolder: $(Build.ArtifactStagingDirectory)
    sourceFolder: '.build/release'
    contents: 'ExampleResponseApp'
- script: ls -l  $(Build.ArtifactStagingDirectory)
  displayName: show contents in $(Build.ArtifactStagingDirectory)
#- task: PublishPipelineArtifact@0
#  inputs:
#    artifactName: 'ExampleResponseApp'
#    targetPath: $(Build.ArtifactStagingDirectory)
- task: PublishBuildArtifacts@1
  inputs:
    artifactName: publish-artifact
    pathtoPublish: $(Build.ArtifactStagingDirectory)
