resources:
  containers:
  - container: ubuntu-build-container
    image: swift:4.2.1

pool:
  vmImage: 'ubuntu-16.04'

container: ubuntu-build-container

steps:
  - script: swift build --configuration release --product ExampleResponseApp
    displayName: building application
  - script: pwd
    displayName: show current directory
  - script: env
    displayName: show environment
  - task: CopyFiles@2
    inputs:
      targetFolder: $(Build.ArtifactStagingDirectory)
      sourceFolder: '.build/release'
      contents: 'ExampleResponseApp'
