resources:
  containers:
  - container: ubuntu-build-container
    image: swift:4.2.1

pool:
  vmImage: 'ubuntu-16.04'

container: ubuntu-build-container

steps:
  - script: swift build --configuration release --product ExampleResponseApp
    displayName: building application
  - task: build-artifacts@0
    inputs:
      targetPath: .build/release/ExampleResponseApp
